services:
  # Flask Backend Service
  - type: web
    name: finance-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_API_SECRET
        sync: false
      - key: FINNHUB_API_KEY
        sync: false

  # Frontend React Service
  - type: web
    name: finance-frontend
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && serve -s build -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 16.0.0
